//# proto-file:
//# proto-message:

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: pb_idl/grpc/grpc.proto

// 假设有如下proto文件

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_UNKNOW Gender = 0
	Gender_MALE   Gender = 1
	Gender_FEMALE Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "UNKNOW",
		1: "MALE",
		2: "FEMALE",
	}
	Gender_value = map[string]int32{
		"UNKNOW": 0,
		"MALE":   1,
		"FEMALE": 2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_idl_grpc_grpc_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_pb_idl_grpc_grpc_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_pb_idl_grpc_grpc_proto_rawDescGZIP(), []int{0}
}

type Grade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                                //整形
	Name   string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                             //字符串
	Gender Gender             `protobuf:"varint,3,opt,name=gender,proto3,enum=test.Gender" json:"gender,omitempty"`                                                                       //枚举类型
	Score  map[string]float32 `protobuf:"bytes,4,rep,name=score,proto3" json:"score,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"` //map映射
}

func (x *Grade) Reset() {
	*x = Grade{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_idl_grpc_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Grade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grade) ProtoMessage() {}

func (x *Grade) ProtoReflect() protoreflect.Message {
	mi := &file_pb_idl_grpc_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grade.ProtoReflect.Descriptor instead.
func (*Grade) Descriptor() ([]byte, []int) {
	return file_pb_idl_grpc_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Grade) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Grade) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Grade) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_UNKNOW
}

func (x *Grade) GetScore() map[string]float32 {
	if x != nil {
		return x.Score
	}
	return nil
}

type GrpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GrpcRequest) Reset() {
	*x = GrpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_idl_grpc_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcRequest) ProtoMessage() {}

func (x *GrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_idl_grpc_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcRequest.ProtoReflect.Descriptor instead.
func (*GrpcRequest) Descriptor() ([]byte, []int) {
	return file_pb_idl_grpc_grpc_proto_rawDescGZIP(), []int{1}
}

type GrpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GrpcResponse) Reset() {
	*x = GrpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_idl_grpc_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcResponse) ProtoMessage() {}

func (x *GrpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_idl_grpc_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcResponse.ProtoReflect.Descriptor instead.
func (*GrpcResponse) Descriptor() ([]byte, []int) {
	return file_pb_idl_grpc_grpc_proto_rawDescGZIP(), []int{2}
}

var File_pb_idl_grpc_grpc_proto protoreflect.FileDescriptor

var file_pb_idl_grpc_grpc_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x62, 0x5f, 0x69, 0x64, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x65, 0x73, 0x74, 0x22, 0xb9,
	0x01, 0x0a, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x06,
	0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x2c, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x2e, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x1a, 0x38, 0x0a, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x72,
	0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x72, 0x70,
	0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x2a, 0x0a, 0x06, 0x47, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x45, 0x4d,
	0x41, 0x4c, 0x45, 0x10, 0x02, 0x32, 0x40, 0x0a, 0x0b, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72,
	0x69, 0x76, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x12, 0x11, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x62, 0x5f, 0x67, 0x65,
	0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_idl_grpc_grpc_proto_rawDescOnce sync.Once
	file_pb_idl_grpc_grpc_proto_rawDescData = file_pb_idl_grpc_grpc_proto_rawDesc
)

func file_pb_idl_grpc_grpc_proto_rawDescGZIP() []byte {
	file_pb_idl_grpc_grpc_proto_rawDescOnce.Do(func() {
		file_pb_idl_grpc_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_idl_grpc_grpc_proto_rawDescData)
	})
	return file_pb_idl_grpc_grpc_proto_rawDescData
}

var file_pb_idl_grpc_grpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_idl_grpc_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_idl_grpc_grpc_proto_goTypes = []interface{}{
	(Gender)(0),          // 0: test.Gender
	(*Grade)(nil),        // 1: test.Grade
	(*GrpcRequest)(nil),  // 2: test.GrpcRequest
	(*GrpcResponse)(nil), // 3: test.GrpcResponse
	nil,                  // 4: test.Grade.ScoreEntry
}
var file_pb_idl_grpc_grpc_proto_depIdxs = []int32{
	0, // 0: test.Grade.gender:type_name -> test.Gender
	4, // 1: test.Grade.score:type_name -> test.Grade.ScoreEntry
	2, // 2: test.GrpcSerivce.SayHello:input_type -> test.GrpcRequest
	3, // 3: test.GrpcSerivce.SayHello:output_type -> test.GrpcResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_idl_grpc_grpc_proto_init() }
func file_pb_idl_grpc_grpc_proto_init() {
	if File_pb_idl_grpc_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_idl_grpc_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Grade); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_idl_grpc_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_idl_grpc_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_idl_grpc_grpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_idl_grpc_grpc_proto_goTypes,
		DependencyIndexes: file_pb_idl_grpc_grpc_proto_depIdxs,
		EnumInfos:         file_pb_idl_grpc_grpc_proto_enumTypes,
		MessageInfos:      file_pb_idl_grpc_grpc_proto_msgTypes,
	}.Build()
	File_pb_idl_grpc_grpc_proto = out.File
	file_pb_idl_grpc_grpc_proto_rawDesc = nil
	file_pb_idl_grpc_grpc_proto_goTypes = nil
	file_pb_idl_grpc_grpc_proto_depIdxs = nil
}
